### ISSUE TITLE
Create a `charter.md` for the Public Sector User Group

### ISSUE THREAD

**Issue by onlydole** [cncf/public-sector-user-group#1]
# CNCF Public Sector User Group Charter

Primary Authors: Taylor Dolezal <I will update with your name as you would like!>

Approved < Date TBD >

Reviewed and contributed to by:

* < Names will be added here >

## **Introduction**

This charter describes the operations of the CNCF Public Sector User Group, which focuses on developing and sharing cloud native practices for public sector organizations that are building and operating cloud native infrastructure or applications.

This user group (UG) produces supporting material and best practices for end users in the public sector and provides guidance and coordination for CNCF projects working within the group's scope.

## **Mission**

The mission of the CNCF Public Sector User Group is to:

* Collaborate on areas related to developing, distributing, deploying, managing and operating secure cloud native workflows that can be used by organizations in the public sector vertical.
* Develop informational resources including guides, tutorials, and white papers to give the community an understanding of best practices, trade-offs, and value-adds.
* Identify useful CNCF projects and contexts.
* Share information about gaps and opportunities for improvement with the CNCF ecosystem.
* <Anything else?>

## **Areas considered in Scope**

The CNCF Public Sector User Group focuses on the following topics of the lifecycle of cloud-native applications:

* <We spoke about airgapped networks and some other items this morning. What would you like to list here?>

The group will work on developing best practices, fostering collaboration between related projects, working on improving tool interoperability, as well as proposing new initiatives and projects when blank spots in the current landscape are identified.

For CNCF projects, the scope of the Public Sector User Group engages, amongst others, with the application management focused ones, for example:

* <We spoke about airgapped networks and some other items this morning. What would you like to list here?>

## **Areas considered out of Scope**

Anything not explicitly considered in the scope above. Example include:

* <I would like to hear your thoughts on these!>

## **Roadmap**

* <Are there any items that make sense to put on our roadmap, or would you like a GitHub Project board for this?>

### Cross-group relationships

Lifecycle management of applications is a broad and mainstream topic of Cloud Native computing; therefore this TAG may collaborate with other CNCF UGs, TAGs, and projects.

## **Contact**

* [Slack Channel (#public-sector-ug)](https://cloud-native.slack.com/archives/C04RQ9L9KFS)
* <Would you like a mailing list? If so, who should we add initially?>

**Comment by riffingonsoftware** [comment]
Beyond air-gapped, we also discussed far edge deployments and an increased interest in topics like security and SBOMs. I'm happy to take a crack at defining far edge if there's value.

I'm not sure if there are areas explicitly out of scope, but I'm happy to be proven wrong. I'm not sure about the Roadmap. I would personally vote against a mailing list, preferring to default to Slack.

**Comment by onlydole** [comment]
No issue at all (pun intended) 😂 thank you, @idunbarh!
